/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AaaBAaaB4WhereInput } from "./AaaBAaaB4WhereInput";
import { Type } from "class-transformer";
import { AaaBAaaB4OrderByInput } from "./AaaBAaaB4OrderByInput";

@ArgsType()
class AaaBAaaB4FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => AaaBAaaB4WhereInput,
  })
  @Field(() => AaaBAaaB4WhereInput, { nullable: true })
  @Type(() => AaaBAaaB4WhereInput)
  where?: AaaBAaaB4WhereInput;

  @ApiProperty({
    required: false,
    type: [AaaBAaaB4OrderByInput],
  })
  @Field(() => [AaaBAaaB4OrderByInput], { nullable: true })
  @Type(() => AaaBAaaB4OrderByInput)
  orderBy?: Array<AaaBAaaB4OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { AaaBAaaB4FindManyArgs as AaaBAaaB4FindManyArgs };
