/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AaaBAaaB4WhereInput } from "./AaaBAaaB4WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class AaaBAaaB4ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => AaaBAaaB4WhereInput,
  })
  @ValidateNested()
  @Type(() => AaaBAaaB4WhereInput)
  @IsOptional()
  @Field(() => AaaBAaaB4WhereInput, {
    nullable: true,
  })
  every?: AaaBAaaB4WhereInput;

  @ApiProperty({
    required: false,
    type: () => AaaBAaaB4WhereInput,
  })
  @ValidateNested()
  @Type(() => AaaBAaaB4WhereInput)
  @IsOptional()
  @Field(() => AaaBAaaB4WhereInput, {
    nullable: true,
  })
  some?: AaaBAaaB4WhereInput;

  @ApiProperty({
    required: false,
    type: () => AaaBAaaB4WhereInput,
  })
  @ValidateNested()
  @Type(() => AaaBAaaB4WhereInput)
  @IsOptional()
  @Field(() => AaaBAaaB4WhereInput, {
    nullable: true,
  })
  none?: AaaBAaaB4WhereInput;
}
export { AaaBAaaB4ListRelationFilter as AaaBAaaB4ListRelationFilter };
