/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { AaaBAaaB4CreateInput } from "./AaaBAaaB4CreateInput";

@ArgsType()
class CreateAaaBAaaB4Args {
  @Field(() => AaaBAaaB4CreateInput, { nullable: false })
  data!: AaaBAaaB4CreateInput;
}

export { CreateAaaBAaaB4Args as CreateAaaBAaaB4Args };
